---
- name: Start fluentd setup tasks
  ansible.builtin.debug:
    msg: "Start fluentd setup tasks"

- name: Install fluentd package
  ansible.builtin.shell: curl -fsSL https://toolbelt.treasuredata.com/sh/install-ubuntu-jammy-td-agent4.sh | sh
