name: Packer

on:
  - pull_request
  - push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Use latest Packer
        uses: hashicorp-contrib/setup-packer@v2
        with:
          packer-version: 1.8.3
      - name: Validate configuration files
        run: |
          packer init .
          packer validate .
#       - name: Build image from template
#         run: packer build TEMPLATE
